// <auto-generated />
namespace AptechProject.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userRolesRomove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userRolesRomove));
        
        string IMigrationMetadata.Id
        {
            get { return "202101240639283_userRolesRomove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
